PALAVRAS = {
  "Países": [
    {"Palavra": "Brasil", "Complexidade": 1},
    {"Palavra": "Argentina", "Complexidade": 2},
    {"Palavra": "Alemanha", "Complexidade": 3},
    {"Palavra": "França", "Complexidade": 2},
    {"Palavra": "Japão", "Complexidade": 3},
    {"Palavra": "Canadá", "Complexidade": 2},
    {"Palavra": "Itália", "Complexidade": 2},
    {"Palavra": "Espanha", "Complexidade": 2},
    {"Palavra": "Rússia", "Complexidade": 3},
    {"Palavra": "China", "Complexidade": 3},
    {"Palavra": "Índia", "Complexidade": 3},
    {"Palavra": "Reino Unido", "Complexidade": 3},
    {"Palavra": "Austrália", "Complexidade": 2},
    {"Palavra": "México", "Complexidade": 2},
    {"Palavra": "África do Sul", "Complexidade": 3},
    {"Palavra": "Nova Zelândia", "Complexidade": 3},
    {"Palavra": "Turquia", "Complexidade": 3},
    {"Palavra": "Suécia", "Complexidade": 2},
    {"Palavra": "Noruega", "Complexidade": 2},
    {"Palavra": "Suíça", "Complexidade": 3}
  ],
  "Verbos": [
    {"Palavra": "Comer", "Complexidade": "1"},
    {"Palavra": "Correr", "Complexidade": "2"},
    {"Palavra": "Estudar", "Complexidade": "3"},
    {"Palavra": "Jogar", "Complexidade": "1"},
    {"Palavra": "Ler", "Complexidade": "1"},
    {"Palavra": "Escrever", "Complexidade": "2"},
    {"Palavra": "Falar", "Complexidade": "1"},
    {"Palavra": "Ouvir", "Complexidade": "1"},
    {"Palavra": "Cantar", "Complexidade": "2"},
    {"Palavra": "Dançar", "Complexidade": "2"},
    {"Palavra": "Nadar", "Complexidade": "2"},
    {"Palavra": "Desenhar", "Complexidade": "3"},
    {"Palavra": "Viajar", "Complexidade": "2"},
    {"Palavra": "Construir", "Complexidade": "3"},
    {"Palavra": "Ajudar", "Complexidade": "1"},
    {"Palavra": "Trabalhar", "Complexidade": "2"},
    {"Palavra": "Vender", "Complexidade": "2"},
    {"Palavra": "Comprar", "Complexidade": "2"},
    {"Palavra": "Pensar", "Complexidade": "2"},
    {"Palavra": "Esperar", "Complexidade": "1"}
  ],
  "Animais": [
    {"Palavra": "Cachorro", "Complexidade": 1},
    {"Palavra": "Gato", "Complexidade": 1},
    {"Palavra": "Elefante", "Complexidade": 3},
    {"Palavra": "Leão", "Complexidade": 2},
    {"Palavra": "Tigre", "Complexidade": 2},
    {"Palavra": "Urso", "Complexidade": 3},
    {"Palavra": "Cavalo", "Complexidade": 2},
    {"Palavra": "Pato", "Complexidade": 1},
    {"Palavra": "Peixe", "Complexidade": 1},
    {"Palavra": "Sapo", "Complexidade": 1},
    {"Palavra": "Coelho", "Complexidade": 1},
    {"Palavra": "Rato", "Complexidade": 1},
    {"Palavra": "Águia", "Complexidade": 2},
    {"Palavra": "Pinguim", "Complexidade": 2},
    {"Palavra": "Tubarão", "Complexidade": 3},
    {"Palavra": "Cobra", "Complexidade": 3},
    {"Palavra": "Jacaré", "Complexidade": 3},
    {"Palavra": "Gorila", "Complexidade": 3},
    {"Palavra": "Raposa", "Complexidade": 2},
    {"Palavra": "Coruja", "Complexidade": 2},
    {"Palavra": "Formiga", "Complexidade": 1}
  ],
  "Frutas": [
    {"Palavra": "Maçã", "Complexidade": 1},
    {"Palavra": "Banana", "Complexidade": 1},
    {"Palavra": "Laranja", "Complexidade": 1},
    {"Palavra": "Uva", "Complexidade": 1},
    {"Palavra": "Morango", "Complexidade": 2},
    {"Palavra": "Abacaxi", "Complexidade": 2},
    {"Palavra": "Pera", "Complexidade": 1},
    {"Palavra": "Kiwi", "Complexidade": 2},
    {"Palavra": "Manga", "Complexidade": 2},
    {"Palavra": "Cereja", "Complexidade": 2},
    {"Palavra": "Limão", "Complexidade": 1},
    {"Palavra": "Framboesa", "Complexidade": 3},
    {"Palavra": "Melancia", "Complexidade": 2},
    {"Palavra": "Coco", "Complexidade": 2},
    {"Palavra": "Maracujá", "Complexidade": 2},
    {"Palavra": "Pêssego", "Complexidade": 2},
    {"Palavra": "Ameixa", "Complexidade": 2},
    {"Palavra": "Mamão", "Complexidade": 2},
    {"Palavra": "Lichia", "Complexidade": 3},
    {"Palavra": "Groselha", "Complexidade": 3},
    {"Palavra": "Tangerina", "Complexidade": 2}
  ]
}
